<footer class="footer">
  <div class="footer-main">
    <div class="footer-grid">

      <div class="footer-logo">
        <img src="images/Swin.png" alt="S1">
        <p>Contact with us</p>
      </div>

      <div class="links">
        <h3>Quick Links</h3>
        <ul>
          <li><a href="index.php">Home</a></li>
          <li><a href="apply.php">Descriptions</a></li>
          <li><a href="jobs.php">Job</a></li>
          <li><a href="about.php">About us</a></li>
          <a href="enhancements.php">Enhancements</a>
        </ul>
      </div>

      <div class="contact">
        <h3>Contact Us</h3>
        <ul>
          <li>1A Bach Dang Street</li>
          <li>info@swintech.com.au</li>
          <li>+1 234 567 890</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="footer-bottom">
    <p>&copy; Copyright 2025 Swintech company. | 
      <a href="https://onepham2005.atlassian.net/jira/software/projects/DDAT/boards/35/timeline">Our Jira Project</a>
      <a href="https://github.com/WebTechnologyProject-Sep2025/projectpart2-cos10026-2-group-2-1.git">Our github</a></p>
    <div class="bottom-links">
      <a href="#">Privacy Policy</a>
      <a href="#">Terms of Service</a>
      <a href="#">Cookie Policy</a>
    </div>
  </div>
</footer>



